### ISSUE TITLE
Request for failure and delta examples

### ISSUE THREAD

**Issue by networkop** [batfish/pybatfish#117]
Hi,
any chance you could add an example of an interface failure and how to work with delta configs?

**Comment by sfraint** [comment]
Hey @networkop , absolutely!

For interface failures, you can upload a snapshot with an interface blacklist, like in the new `live-with-interface-outage` snapshot in the [example network](https://github.com/batfish/batfish/tree/master/networks/example).

For working with comparing two snapshots, you can specify a `snapshot` and `reference_snapshot` when asking questions in Pybatfish.  Checkout the recently added [ACL changes notebook](https://github.com/batfish/pybatfish/blob/master/jupyter_notebooks/Provably%20Safe%20ACL%20and%20Firewall%20Changes.ipynb) for an example, which compares two snapshots in `Step 3`.

Also, feel free to reach out on slack if you have any other questions!
