### ISSUE TITLE
Error out on default parameters

### ISSUE THREAD

**Issue by ratulm** [batfish/pybatfish#222]
pybatfish lets me ask `bfq.nodeProperties("garbage")` and returns an answer happily. It should instead produce an error.

**Comment by progwriter** [comment]
Can you elaborate why? 
The first parameter to `nodeProperties` is nodeSpec. What if you have a node named "garbage" in your network? 
I don't understand the desired behavior nor why this is a pybf bug.

**Comment by ratulm** [comment]
Perhaps that works for the nodeProperties, but it does not seem like that the positional parameters of all the question templates are thought out. The question that tripped me was `resolveNodeSpecifier`, where the supplied parameter value got silently mapped to `questionName` and I got back unexpected answers to my query.  (Sorry, I created confusion by using a different template in the issue than the one with the wrong behavior.) Is pybf currently to be smart about parameter positions?

**Comment by dhalperi** [comment]
@progwriter @ratulm - both of the previous comments seem wrong. Looking at [the code](https://github.com/batfish/pybatfish/blob/c3ec6e23d8ccbc22a48316456e8d70aba571763c/pybatfish/question/question.py#L79-L80), the constructor is defined as:

```py
        def constructor(self, question_name=None,
                        exclusions=None, **kwargs):
        ...
        setattr(new_cls, '__init__', constructor)
```

So the first two positional arguments will always be interpreted as question_name and exclusions, and then after that, positional arguments will not be accepted. Presumably, we could move `question_name` and `exclusions` into the `**kwargs`, and the positional arguments would be gone?

If the project were py3-only, I'd prefer the [`*, a, b, c` formulation](https://stackoverflow.com/a/7624932/1715495).

**Comment by dhalperi** [comment]
Re:
> it does not seem like that the positional parameters of all the question templates are thought out.

Templates store parameters in a JSON map, so there is no ordering. I believe fixing this is on your plate, @ratulm ?

**Comment by dhalperi** [comment]
E.g.,:

```
bfq.nodeProperties("foo", "bar", "baz")
TypeError                                 Traceback (most recent call last)
<ipython-input-7-adc5ec6169d6> in <module>
----> 1 bfq.nodeProperties("foo", "bar", "baz")

TypeError: constructor() takes from 1 to 3 positional arguments but 4 were given
```
