### ISSUE TITLE
Publish to PyPI?

### ISSUE THREAD

**Issue by supertylerc** [batfish/pybatfish#246]
Didn't see an issue for this, apologies if there was one!

Is there a plan to publish this to PyPI, or is the intent to only distribute via GitHub?

Either way, thanks for a great project!

**Comment by corinaminer** [comment]
Hi, thanks for your interest! We do plan to publish this to PyPi in the future, but don’t have a specific target date yet.

**Comment by dhalperi** [comment]
pybatfish is published to pypi
