### ISSUE TITLE
Add method to get batfish server version 

### ISSUE THREAD

**Issue by dgarros** [batfish/pybatfish#309]
Following a discussion with @ratulm on slack

I think it will be useful to be able to get the current version of code running on the batfish server from pybatfish. 
As the project grow, I assume it will become important to provide this information when opening an issue on the batfish project ..

**Comment by dhalperi** [comment]
@sfraint this is done right?

**Comment by sfraint** [comment]
Hey @dgarros , you can use [`Session.get_component_versions()` to query the version of various components](https://github.com/batfish/pybatfish/blob/master/pybatfish/client/session.py#L827), including the release-version of the Batfish service.

e.g.
```
from pybatfish.client.session import Session
bf = Session()
versions = bf.get_component_versions()
print(versions)
```
```
{'Batfish': '2022.09.08.86', 'api_version': '2.1.0'}
```
