### ISSUE TITLE
definedStructures does not take in namedStructureSpecifier

### ISSUE THREAD

**Issue by saparikh** [batfish/pybatfish#397]
https://pybatfish.readthedocs.io/en/latest/questions.html?highlight=namedStructureSpec

`Structure_type` filed in `bfq.definedStructures` is operating on the vendor specific structure type, not vendor independent structure type. Therefore is takes in a `javaregex`, not a `nameStructureSpec`

The docs are incorrect and need to be updated.

**Comment by dhalperi** [comment]
Updated docs
