### ISSUE TITLE
External BGP Feed and Remote Neighbor Examples

### ISSUE THREAD

**Issue by supertylerc** [batfish/pybatfish#419]
I haven't seen this covered in the existing notebooks.  It would be good to see how to couple the external BGP feed and external node/AS features with pybatfish.  I tried simply copying a structure from [here for external BGP feeds](https://github.com/batfish/batfish/tree/master/networks/example/live-with-bgp-announcements) and [here for external physical connectivity](https://github.com/batfish/batfish/tree/master/networks/example/live-with-isp), but it doesn't seem to have worked, or at least not the way I had expected, or I did something else wrong in the process.

For the external BGP feed, I have a JSON file in the root of my snapshot dir.  Its contents are the following:

```json
{
    "Announcements": [
        {
            "type": "ebgp_sent",
            "network": "4.0.0.0/8",
            "nextHopIp": "169.254.0.2",
            "srcNode": "abstractAS",
            "srcIp": "169.254.0.2",
            "dstNode": "router1",
            "dstIp": "169.254.0.1",
            "srcProtocol": "AGGREGATE",
            "originType": "egp",
            "localPreference": 0,
            "med": 20,
            "originatorIp": "0.0.0.0",
            "asPath": [
                [
                    1239
                ],
                [
                    7018,
                    7019
                ]
            ],
            "communities": [],
            "srcVrf": "default",
            "dstVrf": "default",
            "clusterList": []
        }
    ]
}
```

My router has an interface with an IP of `169.254.0.1`.

For the abstract node/AS, I have a file `batfish/stubs.json` to represent my external node.  Its contents:

```json
{
    "borderInterfaces": [
        {
            "borderInterface": {
                "hostname": "router1",
                "interface": "TenGigE0/0/0/0.738"
            }
        }
    ],
    "filter": {
        "onlyRemoteAsns": [],
        "onlyRemoteIps": []
    }
}
```

Any pointers or help would be greatly appreciated.  Thank you for such a great project!

**Comment by ratulm** [comment]
@supertylerc - for ISP / remote neighbors, see the documentation here: https://github.com/batfish/batfish/wiki/Packaging-snapshots-for-analysis#format-for-isp-configuration-json-files. your file format looks correct, but the file name should be `isp_config.json`

**Comment by ratulm** [comment]
@supertylerc - for BGP feed, it could be a similar issue. what file name did you use? (I see that we don't have documentation for this; we'll add it.)

please give these a shot and let us know if things don't work as you expect. 


PS: apologies for the delay in responding

**Comment by saparikh** [comment]
@supertylerc you do not need to provide a stub node for the BGP peer whose announcements you are providing as input. can you try setting `srcProtocol` to `aggregate`? Not sure if we do the right thing on the backend. If that doesn't work, try setting it to `bgp`. 

I haven't tried using external announcements with the ISP config file, that may not work at the moment. If you can try just injecting the BGP routes without defining the `isp_config.json` file that might work.

Also the file name must be `external_bgp_announcements.json` and it should be in the same directory as the `configs/` folder.
