### ISSUE TITLE
How to access the snapshot

### ISSUE THREAD

**Issue by jutkarsh079** [batfish/pybatfish#606]
Hello,
This is not exactly an issue but a query.
Is there any way I can access the snapshot created by the batfish.client.commands.

**Comment by corinaminer** [comment]
Hi @jutkarsh079, unfortunately the Batfish Java client is no longer supported. Instead we have a much more flexible and better-documented Python client, [Pybatfish](https://github.com/batfish/pybatfish). Instructions for getting started with Batfish and Pybatfish are here: https://pybatfish.readthedocs.io/en/latest/getting_started.html

Feel free to join our [open source Slack community](https://join.slack.com/t/batfish-org/shared_invite/enQtMzA0Nzg2OTAzNzQ1LTcyYzY3M2Q0NWUyYTRhYjdlM2IzYzRhZGU1NWFlNGU2MzlhNDY3OTJmMDIyMjQzYmRlNjhkMTRjNWIwNTUwNTQ) -- you'll get faster responses there than with Github issues :) You may also want to look through our [example Jupyter notebooks](https://github.com/batfish/pybatfish/tree/master/jupyter_notebooks) or [videos](https://www.youtube.com/channel/UCA-OUW_3IOt9U_s60KvmJYA).

**Comment by ratulm** [comment]
I believe @jutkarsh079 is already on Slack and we answered the question again.

@jutkarsh079 - re-open/re-ask if this has not been resolved.
