### ISSUE TITLE
Flow: print unusual advanced properties

### ISSUE THREAD

**Issue by dhalperi** [batfish/pybatfish#620]
Flow's printing tries to omit unnecessary properties, but hiding them always causes confusion. User `Bruce DeWald` on Slack had a case where reachability returned flows with both success and failure, but the flows printed the same. Only when we went to the `dict` did it become clear.

Pretty printing for success:

```
Start Location: node1
Src IP: 10.250.53.162
Src Port: 49152
Dst IP: 10.250.53.170
Dst Port: 23
IP Protocol: TCP
```

For failure:
```
Start Location: node1
Src IP: 10.250.53.162
Src Port: 49152
Dst IP: 10.250.53.170
Dst Port: 23
IP Protocol: TCP
```

They are the same

**Comment by ratulm** [comment]
Fixed by https://github.com/batfish/pybatfish/pull/821
