### ISSUE TITLE
Any plan to release 2020.12.23?

### ISSUE THREAD

**Issue by chadell** [batfish/pybatfish#702]
Hi,

Any plan to release version [2020.12.23](https://github.com/batfish/pybatfish/tree/release-2020.12.23.763)?

**Comment by dhalperi** [comment]
Hi @chadell - can I ask what you mean? That release is the latest currently available on pypi: https://pypi.org/project/pybatfish/ and has been there since 12/23.

**Comment by chadell** [comment]
sorry @dhalperi , you are absolutely right. I got confused to not seeing it in the [releases section](https://github.com/batfish/pybatfish/releases).
