### ISSUE TITLE
Document compareRoutePolicies question

### ISSUE THREAD

**Issue by ratulm** [batfish/pybatfish#869]
Couple of things:
1/ The question should show up here: https://pybatfish.readthedocs.io/en/latest/notebooks/differentialQuestions.html
2/ Add to this notebook (https://github.com/batfish/pybatfish/blob/master/jupyter_notebooks/Analyzing%20Routing%20Policies.ipynb) or create a separate one showing usage

1 is higher priority. Once that is done, PR https://github.com/batfish/pybatfish/pull/868 can be reverted. 

PS: Consider making the interface of the question consistent with compareFilters first.

**Comment by dhalperi** [comment]
Do not do this until the question is done.


Right now it's in prototype and not stable API
