### ISSUE TITLE
urllib3 dependency version should be updated to use "allowed_methods" parameter

### ISSUE THREAD

**Issue by SivaKesava1** [batfish/pybatfish#895]
Hello Team,

There was a [recent commit](https://github.com/batfish/pybatfish/commit/74a873a801aacac0c9ae04f47a66d3f690379fef) to use the latest `urllib3` [Retry](https://urllib3.readthedocs.io/en/stable/reference/urllib3.util.html) interface. In the [dependency doc](https://github.com/batfish/pybatfish/blob/c8e8a34fb1fa49c0424e7908415c3617abcd2a45/docs/environment.yml#L75), it still refers to the older version [1.25.8](https://github.com/urllib3/urllib3/releases/tag/1.25.8), and that version seems to not have the argument `'allowed_methods'`. 

I installed `pybatfish`  today using `python3 -m pip install --upgrade pybatfish` and when I ran, I got the error:
```
File \"/usr/local/lib/python3.8/dist-packages/pybatfish/client/restv2helper.py\", line 60, in <module>\n   
max_retries=Retry(\nTypeError: __init__() got an unexpected keyword argument 'allowed_methods'\n",
```

Thanks,
Siva

**Comment by dhalperi** [comment]
1/ What took you to the linked configuration for Sphinx environments? That's not meant to be user facing.
2/ Thanks; you should be able to just run `pip install --upgrade urllib3>=1.25.10`

**Comment by dhalperi** [comment]
Edited to fix version pasted in

**Comment by SivaKesava1** [comment]
I searched for `urllib3` in the repo and came across that and then checked out the `urllib3` source code.

**Comment by dhalperi** [comment]
Ack; that environment yaml file has nothing to do with the versions that users see. A total red herring :)
