### ISSUE TITLE
Clean up documentation of coordinator host and ports

### ISSUE THREAD

**Issue by dhalperi** [batfish/pybatfish#99]
1. In quickstart, we can assume users are running something simple, local. Should not mention advanced features like overriding the coordinator from localhost.

2. We should document how to point pybatfish at another system, for users that need to do so. That should probably be somewhere on a separate page, and more fleshed out.

**Comment by progwriter** [comment]
1) Taken care of in #105 
2) A detailed "advanced" guide still remains to be written.
